spring:
    application:
        name: xcai-service
    profiles:
        active: local
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    data:
        redis:
            database: 1
            host: localhost
            port: 6379
            timeout: 5000
server:
    port: 8700
    servlet:
        context-path: /api